version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10.x
  build:
    commands:
      - sam package --template-file template.yaml --output-template-file package.yaml --s3-bucket aws-devops-course-dinesh
artifacts:
  files:
    - package.yaml